set nocompatible
set ttyfast

filetype plugin indent on
syntax on

set number
set ruler

set autoindent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=-1
set shiftround

set list
set listchars=tab:»\ ,trail:·,nbsp:␣

set ignorecase
set smartcase

set backspace=indent,eol,start
set hidden

set showmode
set showcmd

set incsearch
set hlsearch

set splitbelow
set splitright

" Cursor style, via DECSCUSR. Vim never sets these itself, and all three are
" needed: when t_EI is empty, t_SI and t_SR are never sent.
" 1 -> blinking block
" 2 -> solid block
" 3 -> blinking underscore
" 4 -> solid underscore
" 5 -> blinking vertical bar
" 6 -> solid vertical bar
let &t_SI.="\e[5 q" " INSERT mode
let &t_SR.="\e[3 q" " REPLACE mode
let &t_EI.="\e[2 q" " NORMAL mode (ELSE)

" Vim restores no shape on exit. Append, never assign: t_ti and t_te already
" carry the alternate-screen setup.
let &t_ti.="\e[2 q" " Entering Vim, and returning from :sh, :!cmd or CTRL-Z
let &t_te.="\e[0 q" " Leaving Vim: back to the terminal's default shape

" Put all temporary files under the same directory.
" https://github.com/mhinz/vim-galore#temporary-files
if exists('*mkdir')
  for s:dir in ['backup', 'swap', 'undo', 'info']
    let s:path = $HOME . '/.vim/files/' . s:dir
    if !isdirectory(s:path)
      call mkdir(s:path, 'p')
    endif
  endfor
endif
set backup
set backupdir=$HOME/.vim/files/backup/
set backupext=-vimbackup
set backupskip=
set directory=$HOME/.vim/files/swap//
set updatecount=100
set undofile
set undodir=$HOME/.vim/files/undo/
set viminfo='100,n$HOME/.vim/files/info/viminfo
