[dotfiles]
"~/.config/mise/config.work.toml" = "src/config/mise/config.work.toml"
"~/.local/bin/glean" = "src/local/bin/glean"
"~/.local/bin/glean-auth-login" = "src/local/bin/glean-auth-login"
"~/.gitconfig-work" = "src/gitconfig-work"
